services:

  webview:
    container_name: webview
    build:
      context: .
      dockerfile: ./docker/webview/Dockerfile
    volumes:
      - ./app/webview/src/:/webview/src/
    ports:
      - "${WEBVIEW_PORT}:${WEBVIEW_PORT}"
    restart: always
    env_file:
      - ./app/webview/.env.dev