FROM node:22.7-alpine
RUN apk add --no-cache libc6-compat
RUN apk update
ENV NODE_ENV=development
WORKDIR /webview
COPY ./packages/webview/package.json .
RUN npm install
COPY ./packages/webview .

COPY ./docker/webview/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]